USE [master]
GO

/****** Object:  Database [personal]    Script Date: 15.03.2019 1:10:41 ******/
DROP DATABASE [personal]
GO

/****** Object:  Database [personal]    Script Date: 15.03.2019 1:10:41 ******/
CREATE DATABASE [personal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'personal', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\personal.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'personal_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\personal_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [personal] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [personal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [personal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [personal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [personal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [personal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [personal] SET ARITHABORT OFF 
GO

ALTER DATABASE [personal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [personal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [personal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [personal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [personal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [personal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [personal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [personal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [personal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [personal] SET  DISABLE_BROKER 
GO

ALTER DATABASE [personal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [personal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [personal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [personal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [personal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [personal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [personal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [personal] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [personal] SET  MULTI_USER 
GO

ALTER DATABASE [personal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [personal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [personal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [personal] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [personal] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [personal] SET  READ_WRITE 
GO

